In [56]:
import numpy as np
import pandas as pd

### Initial Load

In [57]:
DATA_PATH  = "./data/Survival_dataset.csv"

df = pd.read_csv(DATA_PATH)
df = df.reindex(sorted(df.columns), axis=1)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Let's see some samples

In [58]:
df.head()

,ALP_first,ALP_last,ALT_first,ALT_last,AST_first,AST_last,Age,Albumin_first,Albumin_last,BUN_first,BUN_last,Bilirubin_first,Bilirubin_last,CCU,CSRU,Cholesterol_first,Cholesterol_last,Creatinine_first,Creatinine_last,DiasABP_first,DiasABP_highest,DiasABP_last,DiasABP_lowest,DiasABP_median,FiO2_first,FiO2_last,GCS_first,GCS_highest,GCS_last,GCS_lowest,GCS_median,Gender,Glucose_first,Glucose_highest,Glucose_last,Glucose_lowest,Glucose_median,HCO3_first,HCO3_last,HCT_first,HCT_last,HR_first,HR_highest,HR_last,HR_lowest,HR_median,Height,In-hospital_death,K_first,K_last,Lactate_first,Lactate_last,Length_of_stay,MAP_first,MAP_highest,MAP_last,MAP_lowest,MAP_median,MechVentDuration,MechVentLast8Hour,MechVentStartTime,Mg_first,Mg_last,NIDiasABP_first,NIDiasABP_highest,NIDiasABP_last,NIDiasABP_lowest,NIDiasABP_median,NIMAP_first,NIMAP_highest,NIMAP_last,NIMAP_lowest,NIMAP_median,NISysABP_first,NISysABP_highest,NISysABP_last,NISysABP_lowest,NISysABP_median,Na_first,Na_last,PaCO2_first,PaCO2_last,PaO2_first,PaO2_last,Platelets_first,Platelets_last,RespRate_first,RespRate_highest,RespRate_last,RespRate_lowest,RespRate_median,SAPS-I,SICU,SOFA,SaO2_first,SaO2_highest,SaO2_last,SaO2_lowest,SaO2_median,Survival,SysABP_first,SysABP_last,Temp_first,Temp_highest,Temp_last,Temp_lowest,Temp_median,TroponinI_first,TroponinI_last,TroponinT_first,TroponinT_last,UrineOutputSum,WBC_first,WBC_last,Weight,Weight_first,Weight_last,pH_first,pH_last,recordid
0,NaN,NaN,NaN,NaN,NaN,NaN,54.0,NaN,NaN,13.0,8.0,NaN,NaN,0,0,NaN,NaN,0.8,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,15.0,14.0,15.0,0.0,205.0,205.0,115.0,115.0,160.0,26.0,28.0,33.7,30.3,73.0,86.0,86.0,58.0,73.0,NaN,0,4.4,4.0,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,1.9,65.0,67.0,55.0,39.0,49.0,92.33,92.33,79.33,58.67,70.000,147.0,157.0,128.0,96.0,110.0,137.0,136.0,NaN,NaN,NaN,NaN,221.0,185.0,19.0,24.0,23.0,12.0,18.0,6,1,1,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,35.1,38.2,37.8,35.1,37.70,NaN,NaN,NaN,NaN,NaN,11.2,9.4,NaN,NaN,NaN,NaN,NaN,132539
1,NaN,NaN,NaN,NaN,NaN,NaN,76.0,NaN,NaN,16.0,21.0,NaN,NaN,0,1,NaN,NaN,0.8,1.3,67.0,81.0,51.0,32.0,59.0,1.0,0.4,3.0,15.0,15.0,3.0,15.0,1.0,105.0,146.0,146.0,105.0,125.5,21.0,24.0,24.7,29.4,88.0,90.0,65.0,65.0,80.0,175.3,0,4.3,3.5,NaN,NaN,8,79.0,100.0,69.0,43.0,79.0,360.0,0.0,71.0,3.1,1.9,38.0,67.0,49.0,38.0,59.0,49.33,88.33,68.33,49.33,78.165,72.0,131.0,107.0,72.0,115.0,139.0,135.0,34.0,46.0,344.0,140.0,164.0,135.0,NaN,NaN,NaN,NaN,NaN,16,0,8,99.0,99.0,97.0,93.0,97.0,-1,105.0,103.0,35.2,37.9,37.1,34.5,37.45,NaN,NaN,NaN,NaN,5.0,7.4,13.3,76.0,80.6,81.6,7.45,7.37,132540
2,127.0,105.0,91.0,75.0,235.0,164.0,44.0,2.7,2.3,8.0,3.0,3.0,2.8,0,0,NaN,NaN,0.4,0.3,81.0,81.0,70.0,52.0,67.0,1.0,0.4,7.0,8.0,5.0,5.0,5.0,0.0,141.0,143.0,143.0,119.0,141.0,24.0,25.0,28.5,29.4,100.0,113.0,71.0,57.0,85.5,NaN,0,3.3,3.7,1.3,0.9,19,107.0,107.0,92.0,72.0,90.0,2160.0,1.0,617.0,1.9,1.7,84.0,95.0,84.0,66.0,79.0,100.30,110.00,103.00,83.33,97.670,133.0,150.0,141.0,111.0,134.0,137.0,138.0,37.0,37.0,65.0,173.0,72.0,113.0,NaN,NaN,NaN,NaN,NaN,21,0,11,95.0,95.0,95.0,95.0,95.0,-1,148.0,126.0,37.8,39.0,37.2,36.7,37.85,NaN,NaN,NaN,NaN,14.0,4.2,6.2,56.7,56.7,56.7,7.51,7.47,132541
3,105.0,105.0,12.0,12.0,15.0,15.0,68.0,4.4,4.4,23.0,10.0,0.2,0.2,0,0,NaN,NaN,0.9,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,15.0,14.0,15.0,1.0,129.0,129.0,117.0,106.0,117.0,28.0,28.0,41.3,36.3,79.0,88.0,79.0,57.0,74.0,180.3,0,4.0,3.8,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.1,1.9,63.0,81.0,81.0,45.0,64.0,86.67,100.70,98.67,68.33,83.670,134.0,140.0,134.0,102.0,120.0,140.0,137.0,NaN,NaN,NaN,NaN,391.0,284.0,19.0,24.0,22.0,6.0,16.0,7,0,1,NaN,NaN,NaN,NaN,NaN,575,NaN,NaN,36.3,37.0,37.0,35.1,36.40,NaN,NaN,NaN,NaN,NaN,11.5,7.9,84.6,84.6,84.6,NaN,NaN,132543
4,NaN,NaN,NaN,NaN,NaN,NaN,88.0,3.3,3.3,45.0,25.0,NaN,NaN,0,0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,15.0,15.0,15.0,0.0,113.0,113.0,92.0,92.0,102.5,18.0,20.0,22.6,30.9,93.0,94.0,68.0,65.0,73.0,NaN,0,6.0,4.1,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.5,1.6,41.0,96.0,42.0,26.0,42.0,75.33,105.70,73.00,52.33,75.330,144.0,157.0,135.0,105.0,131.0,140.0,139.0,NaN,NaN,NaN,NaN,109.0,97.0,24.0,27.0,16.0,13.0,19.0,17,0,2,NaN,NaN,NaN,NaN,NaN,918,NaN,NaN,37.8,37.8,36.7,35.8,37.00,NaN,NaN,NaN,NaN,NaN,3.8,4.8,NaN,NaN,NaN,NaN,NaN,132545

There are many NaN values in the dataset.

In [14]:
print(df.isna().sum())

ALP_first            2310
ALP_last             2310
ALT_first            2279
ALT_last             2279
AST_first            2275
AST_last             2275
Age                     0
Albumin_first        2385
Albumin_last         2385
BUN_first              64
BUN_last               64
Bilirubin_first      2282
Bilirubin_last       2282
CCU                     0
CSRU                    0
Cholesterol_first    3695
Cholesterol_last     3695
Creatinine_first       64
Creatinine_last        64
DiasABP_first        1221
DiasABP_highest      1221
DiasABP_last         1221
DiasABP_lowest       1221
DiasABP_median       1221
FiO2_first           1283
FiO2_last            1283
GCS_first              64
GCS_highest            64
GCS_last               64
GCS_lowest             64
GCS_median             64
Gender                  3
Glucose_first         113
Glucose_highest       113
Glucose_last          113
Glucose_lowest        113
Glucose_median        113
HCO3_first             76
HCO3_last              76
HCT_first              64
HCT_last               64
HR_first               63
HR_highest             63
HR_last                63
HR_lowest              63
HR_median              63
Height               1894
In-hospital_death       0
K_first                96
K_last                 96
Lactate_first        1817
Lactate_last         1817
Length_of_stay          0
MAP_first            1208
MAP_highest          1208
MAP_last             1208
MAP_lowest           1208
MAP_median           1208
MechVentDuration     1471
MechVentLast8Hour    1471
MechVentStartTime    1471
Mg_first              103
Mg_last               103
NIDiasABP_first       518
NIDiasABP_highest     518
NIDiasABP_last        518
NIDiasABP_lowest      518
NIDiasABP_median      518
NIMAP_first           520
NIMAP_highest         520
NIMAP_last            520
NIMAP_lowest          520
NIMAP_median          520
NISysABP_first        515
NISysABP_highest      515
NISysABP_last         515
NISysABP_lowest       515
NISysABP_median       515
Na_first               75
Na_last                75
PaCO2_first           977
PaCO2_last            977
PaO2_first            977
PaO2_last             977
Platelets_first        68
Platelets_last         68
RespRate_first       2899
RespRate_highest     2899
RespRate_last        2899
RespRate_lowest      2899
RespRate_median      2899
SAPS-I                  0
SICU                    0
SOFA                    0
SaO2_first           2208
SaO2_highest         2208
SaO2_last            2208
SaO2_lowest          2208
SaO2_median          2208
Survival                0
SysABP_first         1220
SysABP_last          1220
Temp_first             64
Temp_highest           64
Temp_last              64
Temp_lowest            64
Temp_median            64
TroponinI_first      3795
TroponinI_last       3795
TroponinT_first      3137
TroponinT_last       3137
UrineOutputSum       1471
WBC_first              92
WBC_last               92
Weight                331
Weight_first         1282
Weight_last          1282
pH_first              962
pH_last               962
recordid                0
dtype: int64

### Dataset Description

In [59]:
df.describe()

,ALP_first,ALP_last,ALT_first,ALT_last,AST_first,AST_last,Age,Albumin_first,Albumin_last,BUN_first,BUN_last,Bilirubin_first,Bilirubin_last,CCU,CSRU,Cholesterol_first,Cholesterol_last,Creatinine_first,Creatinine_last,DiasABP_first,DiasABP_highest,DiasABP_last,DiasABP_lowest,DiasABP_median,FiO2_first,FiO2_last,GCS_first,GCS_highest,GCS_last,GCS_lowest,GCS_median,Gender,Glucose_first,Glucose_highest,Glucose_last,Glucose_lowest,Glucose_median,HCO3_first,HCO3_last,HCT_first,HCT_last,HR_first,HR_highest,HR_last,HR_lowest,HR_median,Height,In-hospital_death,K_first,K_last,Lactate_first,Lactate_last,Length_of_stay,MAP_first,MAP_highest,MAP_last,MAP_lowest,MAP_median,MechVentDuration,MechVentLast8Hour,MechVentStartTime,Mg_first,Mg_last,NIDiasABP_first,NIDiasABP_highest,NIDiasABP_last,NIDiasABP_lowest,NIDiasABP_median,NIMAP_first,NIMAP_highest,NIMAP_last,NIMAP_lowest,NIMAP_median,NISysABP_first,NISysABP_highest,NISysABP_last,NISysABP_lowest,NISysABP_median,Na_first,Na_last,PaCO2_first,PaCO2_last,PaO2_first,PaO2_last,Platelets_first,Platelets_last,RespRate_first,RespRate_highest,RespRate_last,RespRate_lowest,RespRate_median,SAPS-I,SICU,SOFA,SaO2_first,SaO2_highest,SaO2_last,SaO2_lowest,SaO2_median,Survival,SysABP_first,SysABP_last,Temp_first,Temp_highest,Temp_last,Temp_lowest,Temp_median,TroponinI_first,TroponinI_last,TroponinT_first,TroponinT_last,UrineOutputSum,WBC_first,WBC_last,Weight,Weight_first,Weight_last,pH_first,pH_last,recordid
count,1690.000000,1690.000000,1721.000000,1721.000000,1725.000000,1725.000000,4000.000000,1615.000000,1615.000000,3936.000000,3936.000000,1718.000000,1718.000000,4000.000000,4000.00000,305.000000,305.000000,3936.000000,3936.000000,2779.000000,2779.000000,2779.000000,2779.000000,2779.000000,2717.000000,2717.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,3997.000000,3887.000000,3887.000000,3887.000000,3887.000000,3887.000000,3924.000000,3924.000000,3936.000000,3936.000000,3937.000000,3937.000000,3937.000000,3937.000000,3937.000000,2106.000000,4000.000000,3904.000000,3904.000000,2183.000000,2183.000000,4000.000000,2792.000000,2792.000000,2792.000000,2792.000000,2792.000000,2529.000000,2529.000000,2529.000000,3897.000000,3897.000000,3482.000000,3482.000000,3482.000000,3482.000000,3482.000000,3480.000000,3480.000000,3480.000000,3480.000000,3480.000000,3485.000000,3485.000000,3485.000000,3485.000000,3485.000000,3925.000000,3925.000000,3023.000000,3023.000000,3023.000000,3023.000000,3932.000000,3932.000000,1101.000000,1101.000000,1101.000000,1101.000000,1101.000000,4000.000000,4000.000000,4000.000000,1792.000000,1792.000000,1792.000000,1792.000000,1792.000000,4000.000000,2780.000000,2780.000000,3936.000000,3936.000000,3936.000000,3936.000000,3936.000000,205.000000,205.000000,863.000000,863.000000,2529.000000,3908.000000,3908.000000,3669.000000,2718.000000,2718.000000,3038.00000,3038.000000,4000.000000
mean,105.868639,104.302367,155.802440,175.110982,226.927536,222.487536,64.247500,2.989040,2.952570,25.892022,25.399390,1.886321,1.936380,0.144250,0.21850,156.609836,156.537705,1.367683,1.368928,62.370637,83.590140,61.210148,44.494063,59.591220,0.786441,0.499838,10.031250,13.528201,12.370935,8.222561,11.995808,0.561921,149.448932,173.592745,128.435297,108.587857,133.547852,23.150102,24.267329,31.929802,30.862144,89.626670,112.397562,85.998476,68.623343,86.383541,171.985856,0.138500,4.178356,4.067085,2.582666,1.943784,13.441750,84.759312,118.431948,82.361032,58.439470,80.036891,1912.005140,0.620799,285.176750,1.938542,2.048473,60.327111,79.304997,57.536186,40.814474,56.786760,79.329799,96.761922,76.832445,59.692681,75.899545,121.248494,144.191105,119.194835,94.309613,117.635581,138.789809,138.844841,41.523321,40.073106,204.102216,117.419120,215.928535,192.542701,20.161671,29.300636,19.897366,12.345141,19.449137,14.203500,0.267000,6.402500,96.629688,97.643973,96.494978,94.827790,96.765904,128.735500,123.896763,122.461871,36.570574,37.929187,37.046265,35.887688,37.054060,7.185366,6.466341,1.072048,1.002283,12.314749,12.914785,12.303224,81.474832,84.411626,85.037344,7.36812,7.398693,137605.122000
std,111.256601,112.679714,624.938056,668.780132,939.288020,912.158026,17.560946,0.654796,0.646977,21.842378,20.671105,4.425404,4.596338,0.351387,0.41328,46.421643,46.291120,1.489039,1.416127,14.093438,17.466415,13.778136,10.056941,9.577215,0.252746,0.158263,4.892469,2.596492,3.618969,4.805520,3.579082,0.496213,76.710704,87.962849,41.257310,29.886359,38.004392,4.624205,4.267459,6.025011,4.664707,19.988417,22.156625,17.163238,14.094210,15.008135,83.781865,0.345467,0.717245,0.518932,2.109934,1.582990,12.246371,27.334167,36.713954,19.333744,16.586567,13.896759,872.032383,0.485284,484.275957,0.479516,0.315559,17.146365,19.307652,14.945116,12.791638,12.095699,17.805071,18.917398,15.069530,13.037874,12.441490,26.052026,26.412327,22.244652,19.675590,19.036852,4.699957,4.315906,10.675313,8.407649,123.809523,50.320337,113.648096,103.021512,6.164357,7.542093,5.587112,3.373270,4.033288,6.088584,0.442448,4.201298,4.380482,3.121659,3.539673,5.511473,3.361817,363.714273,27.433346,23.676777,1.045933,0.747219,0.726616,0.817756,0.598287,10.573236,9.594861,2.974715,2.395043,5.896841,7.837513,6.591505,23.305130,24.476347,24.090094,0.09346,0.061213,2923.608886
min,12.000000,12.000000,1.000000,3.000000,5.000000,4.000000,15.000000,1.100000,1.000000,0.000000,2.000000,0.100000,0.100000,0.000000,0.00000,28.000000,28.000000,0.200000,0.100000,4.000000,22.000000,5.000000,1.000000,22.000000,0.210000,0.210000,3.000000,3.000000,3.000000,3.000000,3.000000,0.000000,10.000000,60.000000,23.000000,10.000000,49.000000,5.000000,9.000000,12.500000,11.800000,32.000000,53.000000,21.000000,3.500000,40.000000,121.900000,0.000000,1.800000,2.500000,0.400000,0.300000,-1.000000,1.000000,4.000000,2.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.600000,1.100000,10.000000,26.000000,10.000000,3.000000,22.000000,18.000000,39.670000,29.670000,7.000000,36.670000,2.000000,2.000000,1.000000,1.000000,2.000000,98.000000,119.000000,11.000000,16.000000,20.000000,24.000000,8.000000,12.000000,7.000000,16.000000,4.000000,1.000000,9.500000,-1.000000,0.000000,-1.000000,26.000000,46.000000,46.000000,26.000000,40.000000,-1.000000,7.000000,7.000000,29.900000,35.600000,33.700000,26.700000,33.400000,0.300000,0.300000,0.010000,0.010000,1.000000,1.000000,1.000000,35.000000,35.000000,35.000000,6.82000,7.030000,132539.000000
25%,57.000000,57.000000,17.000000,17.000000,25.000000,25.000000,52.750000,2.500000,2.500000,13.000000,12.000000,0.400000,0.400000,0.000000,0.00000,123.000000,123.000000,0.700000,0.700000,53.000000,72.000000,52.000000,38.000000,53.000000,0.500000,0.400000,5.000000,12.000000,10.000000,3.000000,10.000000,0.000000,108.000000,126.000000,102.000000,90.000000,109.000000,21.000000,22.000000,27.900000,27.600000,76.000000,96.000000,74.000000,60.000000,76.000000,162.600000,0.000000,3.700000,3.700000,1.300000,1.200000,6.000000,71.000000,98.000000,71.000000,51.000000,72.000000,1170.000000,0.000000,53.000000,1.700000,1.800000,48.000000,66.000000,47.000000,32.000000,48.500000,67.000000,84.000000,66.330000,51.000000,67.330000,103.000000,126.000000,103.000000,82.000000,103.500000,136.000000,136.000000,35.000000,35.000000,97.000000,86.000000,141.000000,124.000000,16.000000,25.000000,16.000000,10.000000,17.000000,11.000000,0.000000,3.000000,97.000000,98.000000,96.000000,94.000000,96.500000,-1.000000,105.000000,106.000000,35.900000,37.400000,36.600000,35.500000,36.700000,0.700000,0.700000,0.040000,0.040000,8.000000,8.400000,8.500000,66.000000,67.725000,68.500000,7.32000,7.370000,135075.750000
50%,79.000000,78.000000,31.000000,31.000000,46.000000,44.000000,67.000000,3.000000,3.000000,19.000000,19.000000,0.700000,0.700000,0.000000,0.00000,153.000000,152.000000,0.900000,0.900000,61.000000,81.000000,60.000000,44.000000,58.000000,1.000000,0.500000,11.000000,15.000000,15.000000,7.000000,14.000000,1.000000,132.000000,151.000000,121.000000,106.000000,127.000000,23.000000,24.000000,31.700000,30.400000,88.000000,110.000000,85.000000,68.000000,86.000000,170.200000,0.000000,4.100000,4.000000,1.900000,1.600000,10.000000,82.000000,109.000000,80.000000,58.000000,78.000000,2320.000000,1.000000,122.000000,1.900000,2.000000,59.000000,79.000000,56.000000,40.000000,56.000000,77.670000,95.670000,75.330000,58.670000,74.330000,119.000000,142.000000,117.000000,92.000000,115.000000,139.000000,139.000000,40.000000,39.000000,168.000000,106.000000,197.000000,174.000000,19.000000,28.000000,19.000000,12.000000,19.000000,15.000000,0.000000,6.000000,98.000000,98.000000,97.000000,96.000000,97.500000,-1.000000,121.000000,121.000000,36.600000,37.800000,37.000000,36.000000,37.050000,2.200000,2.000000,0.130000,0.130000,13.000000,11.500000,11.200000,78.700000,81.150000,82.200000,7.38000,7.400000,137592.500000
75%,112.000000,109.000000,67.000000,67.000000,104.000000,98.000000,78.000000,3.500000,3.400000,30.000000,31.000000,1.300000,1.400000,0.000000,0.00000,188.000000,188.000000,1.400000,1.400000,71.000000,92.000000,69.000000,50.000000,65.500000,1.000000,0.500000,15.000000,15.000000,15.000000,14.000000,15.000000,1.000000,166.000000,192.000000,144.000000,124.000000,149.000000,26.000000,27.000000,36.000000,33.500000,102.000000,125.000000,97.000000,77.000000,96.000000,177.800000,0.000000,4.500000,4.400000,3.000000,2.200000,17.000000,94.000000,126.000000,91.000000,65.000000,86.000000,2670.000000,1.000000,242.000000,2.200000,2.200000,70.000000,91.000000,67.000000,48.000000,64.000000,90.000000,107.700000,86.000000,67.000000,83.000000,137.000000,160.000000,134.000000,105.000000,130.000000,141.000000,141.000000,46.000000,44.000000,302.000000,137.000000,266.000000,236.000000,23.000000,32.000000,23.000000,14.000000,22.000000,18.000000,1.000000,9.000000,98.000000,99.000000,98.000000,98.000000,98.000000,16.000000,140.000000,138.000000,37.200000,38.400000,37.500000,36.400000,37.400000,8.800000,7.900000,0.555000,0.760000,16.000000,15.600000,14.800000,92.000000,96.600000,97.600000,7.43000,7.440000,140100.250000
max,1752.000000,2205.000000,9890.000000,8980.000000,16040.000000,15680.000000,90.000000,5.300000,5.300000,197.000000,173.000000,45.500000,47.700000,1.000000,1.00000,330.000000,330.000000,22.100000,13.900000,141.000000,188.000000,142.000000,97.000000,104.000000,1.000000,1.000000,15.000000,15.000000,15.000000,15.000000,15.000000,1.000000,1143.000000,1143.000000,599.000000,298.000000,430.000000,47.000000,50.000000,61.800000,60.300000,216.000000,219.000000,176.000000,115.000000,142.000000,3960.000000,1.000000,9.800000,7.600000,24.700000,23.700000,154.000000,294.000000,300.000000,265.000000,265.000000,265.000000,2870.000000,1.000000,2859.000000,9.900000,4.300000,168.000000,201.000000,168.000000,103.000000,110.000000,171.000000,209.000000,178.000000,121.000000,132.000000,252.000000,296.000000,234.000000,234.000000,234.000000,177.000000,165.000000,99.000000,100.000000,500.000000,500.000000,1047.000000,918.000000,91.000000,98.000000,69.000000,26.000000,40.000000,34.000000,1.000000,22.000000,100.000000,100.000000,100.000000,100.000000,100.000000,2600.000000,262.000000,260.000000,40.400000,42.100000,40.900000,38.800000,39.800000,49.200000,49.200000,24.910000,24.040000,44.000000,187.500000,162.000000,280.000000,280.000000,280.000000,7.63000,7.660000,142673.000000

### Correlations of Time Series values

In [16]:
param = "Glucose"
cols = [x for x in df.columns if x[:len(param)] == param]
X_hat = df[cols]
X_hat[f"{param}"] = X_hat[f"{param}_last"] + X_hat[f"{param}_first"]
X_hat.corr()

C:\Users\User\AppData\Local\Temp\ipykernel_7924\3802215248.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_hat[f"{param}"] = X_hat[f"{param}_last"] + X_hat[f"{param}_first"]

,Glucose_first,Glucose_highest,Glucose_last,Glucose_lowest,Glucose_median,Glucose
Glucose_first,1.000000,0.789003,0.204660,0.283873,0.573553,0.903542
Glucose_highest,0.789003,1.000000,0.367537,0.169486,0.607122,0.803103
Glucose_last,0.204660,0.367537,1.000000,0.579028,0.619123,0.604349
Glucose_lowest,0.283873,0.169486,0.579028,1.000000,0.638169,0.484537
Glucose_median,0.573553,0.607122,0.619123,0.638169,1.000000,0.737874
Glucose,0.903542,0.803103,0.604349,0.484537,0.737874,1.000000

### Picking the output

Initially, we want to predict the ```In-hospital death``` variable. That means keeping it as ```y``` column and dropping other outcome-related variables. These are

* RecordID
* SAPS-I score
* SOFA score
* Length of stay (days)
* Survival (days)
* In-hospital death (0: survivor, or 1: died in-hospital)

In [60]:
drop_cols = ["recordid", "SAPS-I", "SOFA", "Length_of_stay", "Survival"]
y_col = "In-hospital_death"

X, y = df.drop(columns = drop_cols + [y_col]), df[y_col]

In [61]:
X_PATH = "./data/Train.csv"
y_PATH = "./data/y.csv"

X.to_csv(X_PATH, index=False)
y.to_csv(y_PATH, index=False)